add restore and make user more customizable with Page::class
shuvroroy/filament-spatie-laravel-backup pull request #76
Opened 2024-07-20 04:38 UTC by Khant-Nyar

- restore  a disk of a row
- show and hide optional for download and delete button at table

2024-08-23 18:16 UTC, jhoanborges commented
+1

2024-08-23 22:03 UTC, jhoanborges commented on src/Components/BackupDestinationListRecords.php
> +                        ])
Add `'--reset' => true,` or maybe pass it as params, otherwise you'll get an error that you have duplicate lines in your database.

2024-09-01 20:23 UTC, Khant-Nyar commented on src/Components/BackupDestinationListRecords.php
> +                        ])
Thanks for reminded me ,I forget to update it I already changed in my prod project.

2025-05-13 13:41 UTC, zhinea commented
+1

2025-05-13 13:45 UTC, zhinea requested changes

2025-05-13 13:45 UTC, zhinea commented on src/Components/BackupDestinationListRecords.php
> +                        ])
Hi! any update for this pull-req?

2025-05-14 03:05 UTC, Khant-Nyar commented on src/Components/BackupDestinationListRecords.php
> +                        ])
> Hi! any update for this pull-req?

ohh ! I am sorry and i can't merge it cause i'm not a official contributor.may be my code was not good or don't follow there rules.by the way i will update my code tonight to ready for merge and keep up to date.

2026-08-24 16:47 UTC, closed without merging